Repository padaiyal/jMavenProjectTemplate, pull requests merged in 2021-01, with the labels that each got.

#5 Add Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#11 Added an action to publish to GitHub packages
  .github/workflows/package_publish.yml
Labels: continuous deployment

#13 Add README.md template
  README.md
Labels: documentation

#15 Fix alignment issue in package_publish.yml
  .github/workflows/package_publish.yml
Labels: continuous deployment

#17 Add distribution management to the pom.xml and package release badge to the README
  README.md
  pom.xml
Labels: bug, documentation

#19 Enable error and debug logging for publishing github packages
  .github/workflows/package_publish.yml
Labels: continuous deployment, enhancement

#21 Rename artifact ID
  pom.xml
Labels: bug, continuous deployment

#25 Cache the local maven repositories in the GitHub action runners
  .github/workflows/maven_macos.yml
  .github/workflows/maven_ubuntu.yml
  .github/workflows/maven_windows.yml
Labels: continuous integration, enhancement

#27 Fixed an issue where PMD checks aren't run as a part of GitHub actions
  .github/workflows/maven_macos.yml
  .github/workflows/maven_ubuntu.yml
  .github/workflows/maven_windows.yml
  .github/workflows/package_publish.yml
Labels: bug

#29 Updated version in pom.xml
  pom.xml
Labels: bug

#32 Fixed LICENSE link in README.md
  README.md
  pom.xml
Labels: bug

#33 Added checkpoint in PR template for verifying pom.xml version.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: continuous integration, documentation

#36 Removed line breaks for each section in issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_or_enhancement_request.md
  pom.xml
Labels: documentation
